# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-24 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(default=b'', max_length=200)),
                ('number', models.CharField(default=b'', max_length=10)),
            ],
        ),
    ]
